#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED


// Window

const int WINDOW_WIDTH = 1280;
const int WINDOW_HEIGHT = 720;
const char WINDOW_TITLE[] = "Bomb Fighter";

// Player

const int PLAYER_INITIAL_HEALTH = 100;
const int PLAYER_INITIAL_SPEED = WINDOW_WIDTH / 50;
const int PLAYER_INITIAL_MAX_BOMB = 2;

const char PLAYER_DIRECTION_UP = '2';
const char PLAYER_DIRECTION_LEFT = '4';
const char PLAYER_DIRECTION_RIGHT = '6';
const char PLAYER_DIRECTION_DOWN = '8';

const int PLAYER1_INITIAL_X = WINDOW_WIDTH / 4;
const int PLAYER1_INITIAL_Y = WINDOW_HEIGHT / 2;
const int PLAYER2_INITIAL_X = WINDOW_WIDTH - PLAYER1_INITIAL_X;
const int PLAYER2_INITIAL_Y = PLAYER1_INITIAL_Y;

// Bomb
const int BOMB_INITIAL_TIME = 5;
const int BOMB_INITIAL_RADIUS = WINDOW_WIDTH / 100;
const int BOMB_INITIAL_SPEED = WINDOW_WIDTH / 20;

#endif // CONSTANTS_H_INCLUDED
