#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED


const char GAME_TITLE[] = "Bomb Fighter";

// Window

const int WINDOW_INITIAL_WIDTH = 1280;
const int WINDOW_INITIAL_HEIGHT = 720;
const int WINDOW_INITIAL_FPS = 240;

// Player

const int PLAYER_INITIAL_HEALTH = 100;
const int PLAYER_INITIAL_SPEED = WINDOW_INITIAL_WIDTH / 50;
const int PLAYER_INITIAL_MAX_BOMB = 2;

const char PLAYER_DIRECTION_UP = '2';
const char PLAYER_DIRECTION_LEFT = '4';
const char PLAYER_DIRECTION_RIGHT = '6';
const char PLAYER_DIRECTION_DOWN = '8';

const int PLAYER1_INITIAL_X = WINDOW_INITIAL_WIDTH / 4;
const int PLAYER1_INITIAL_Y = WINDOW_INITIAL_HEIGHT / 2;
const int PLAYER2_INITIAL_X = WINDOW_INITIAL_WIDTH - PLAYER1_INITIAL_X;
const int PLAYER2_INITIAL_Y = PLAYER1_INITIAL_Y;

// Bomb
const int BOMB_INITIAL_TIME = 5;
const int BOMB_INITIAL_RADIUS = WINDOW_INITIAL_WIDTH / 100;
const int BOMB_INITIAL_SPEED = WINDOW_INITIAL_WIDTH / 20;

// Resources
const char RESOURCE_BACKGROUND_PATH[] = "res/image/background.jpg";

#endif // CONSTANTS_H_INCLUDED
